### Crear libro
POST http://localhost:5000/api-test/libros
Content-Type: application/json

{
  "titulo": "Clean Code",
  "autor": "Robert C. Martin",
  "genero": "Programación",
  "anio_publicacion": 2008,
  "url": "https://ejemplo.com/cleancode",
  "notas": "Un libro muy útil sobre buenas prácticas",
  "etiquetas": "código, buenas prácticas, clean code",
  "usuario_id": 1
}
